import '@/app/globals.css'
import { StoreProvider } from '@/app/providers'
import { Toast } from '@heroui/react'
import { Footer, Header } from '@widgets/index'
import type { Metadata } from 'next'
import { cookies } from 'next/headers'

export const metadata: Metadata = {
  title: 'Speil reviewer',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const cookieTheme = cookieStore.get('theme')?.value
  const initialTheme = cookieTheme === 'dark' ? 'dark' : 'light'

  return (
    <html lang="ru" className="flex h-full flex-col antialiased" data-theme={initialTheme}>
      <StoreProvider initialTheme={initialTheme}>
        <Toast.Provider placement="top" />
        <body className="flex min-h-full flex-col justify-between">
          <Header />
          <main className="flex-1 py-16">{children}</main>
          <Footer />
        </body>
      </StoreProvider>
    </html>
  )
}
