import { Footer, Header } from '@widgets/index'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { cookies } from 'next/headers'
import './globals.css'
import { StoreProvider } from './providers/StoreProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Speil reviewer',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const cookieTheme = cookieStore.get('theme')?.value
  const initialTheme = cookieTheme === 'dark' ? 'dark' : 'light'

  return (
    <html
      lang="ru"
      className={`${geistSans.variable} ${geistMono.variable} flex h-full flex-col antialiased`}
      data-theme={initialTheme}
    >
      <StoreProvider initialTheme={initialTheme}>
        <body className="flex min-h-full flex-col justify-between">
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </StoreProvider>
    </html>
  )
}
