import '@app/globals.css'
import { StoreProvider } from '@app/providers'
import { Toast } from '@heroui/react'
import { routing } from '@i18n/routing'
import { Footer, Header } from '@widgets/index'
import type { Metadata } from 'next'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { cookies } from 'next/headers'
import { notFound } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Speil reviewer',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  const cookieStore = await cookies()
  const cookieTheme = cookieStore.get('theme')?.value
  const initialTheme = cookieTheme === 'dark' ? 'dark' : 'light'

  return (
    <html lang={locale} className="flex h-full flex-col antialiased" data-theme={initialTheme}>
      <body className="flex min-h-full flex-col justify-between">
        <NextIntlClientProvider>
          <StoreProvider initialTheme={initialTheme}>
            <Toast.Provider placement="top" />
            <Header />
            <main className="flex-1 py-16">{children}</main>
            <Footer />
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
